import { BasicACLOptions } from './basic-acl.interfaces';
import { CreateUserInput } from './dto/create-user-input.dto';
import { CreateUserOutput } from './dto/create-user-output.dto';
import { GetUserInput } from './dto/get-user-uid-input.dto';
import { GetUserOutput } from './dto/get-user-output.dto';
import { SendResetPasswordEmailInput } from './dto/send-reset-password-email-input.dto';
import { SendResetPasswordOutput } from './dto/send-reset-password-output.dto';
import { ChangeEmailInput } from './dto/change-email-input.dto';
import { ChangeEmailOutput } from './dto/change-email-output.dto';
import { ChangePasswordInput } from './dto/change-password-input.dto';
import { ChangePasswordOutput } from './dto/change-password-output.dto';
import { ChangePhoneInput } from './dto/change-phone-input.dto';
import { ChangePhoneOutput } from './dto/change-phone-output.dto';
import { DeleteUserOutput } from './dto/delete-user-output.dto';
import { CheckPermissionInput } from './dto/check-permission-input.dto';
import { CheckPermissionOutput } from './dto/check-permission-output.dto';
import { AssignRoleInput } from './dto/assign-user-role-input.dto';
import { AssignRoleOutput } from './dto/assign-role-output.dto';
import { UnassignRoleInput } from './dto/unassign-user-role-input.dto';
import { UnassignUserRoleOutput } from './dto/unassign-user-role-output.dto';
import { GetUsersByAuthUidsInput } from './dto/get-users-by-auth-uids-input.dto';
import { GetUsersByAuthUidsOutput } from './dto/get-users-by-auth-uids-output.dto';
export declare class BasicAclService {
    private readonly options;
    private graphQLClient;
    constructor(options: BasicACLOptions);
    private initGraphQLClient;
    createUser(input: CreateUserInput): Promise<CreateUserOutput>;
    getUser(input: GetUserInput): Promise<GetUserOutput>;
    sendResetPasswordEmail(input: SendResetPasswordEmailInput): Promise<SendResetPasswordOutput>;
    changeEmail(input: ChangeEmailInput): Promise<ChangeEmailOutput>;
    changePassword(input: ChangePasswordInput): Promise<ChangePasswordOutput>;
    changePhone(input: ChangePhoneInput): Promise<ChangePhoneOutput>;
    deleteUser(input: GetUserInput): Promise<DeleteUserOutput>;
    checkPermission(input: CheckPermissionInput): Promise<CheckPermissionOutput>;
    assignRole(input: AssignRoleInput): Promise<AssignRoleOutput>;
    unassignRole(input: UnassignRoleInput): Promise<UnassignUserRoleOutput>;
    getUsersByAuthUids(input: GetUsersByAuthUidsInput): Promise<GetUsersByAuthUidsOutput[]>;
}
